---
engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          paths:
            - "goodplay/**/*"
    exclude_paths:
      - "tests/**/*"
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "B"
ratings:
  paths:
    - "**.py"
exclude_paths:
  - ".*"
  - "docs/source/conf.py"
